### ISSUE TITLE
Zip file upload to data stream endpoint fails

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-webservices-spring#104]
When uploading a zip file to the data stream endpoint, it fails with a 

```
[log] [CAMS DEBUG] RESPONSE: 500
      {"statusCode":500,"exception":"java.lang.NullPointerException","message":"Cannot invoke \"org.springframework.web.multipart.MultipartFile.getBytes()\" because \"zipFile\" is null","path":"POST /api/data-stream-service-zip"}
````

complaining that there is no zip file. 

But - as you can see from my debug window, there is a file in the POST request:

![image](https://github.com/user-attachments/assets/aaa73742-529f-472f-94ed-0b8ad4dab93a)

In general, there is no documentation (as I can see) on exactly how the HTTP request should look like (headers, content types, etc).

**Comment by yuanchen233** [comment]
As discussed, the compressed data does not require to be a separate file. We will use `ByteArray`, Gzip compressed Json.
A endpoint for testing purposes is available 
POST [/api/data/zip](https://dev.carp.dk/doc/swagger-ui/index.html#/data-stream-controller/handleCompressedData)

This endpoint is tested using binary data achieved from 
```node.js
function createGzipFile(filename, jsonData) {
    const jsonString = JSON.stringify(jsonData);
    const buffer = Buffer.from(jsonString, 'utf-8');
    zlib.gzip(buffer, (err, compressedBuffer) => {
        if (err) {
            console.error(err);
            return;
            }
        // File created only for testing purposes
        fs.writeFileSync(filename, compressedBuffer);
    });
}
```

However, if we decided to used this method, the ByteArray should be handled by a [HttpMessageConverter<T>](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/converter/HttpMessageConverter.html) in the backend, before the request reach controller

**Comment by bardram** [comment]
Just tested with a small payload and it seems to work.

**Comment by bardram** [comment]
Just tested uploading 10 unique measurements - and got them back again. All good.

**Comment by yuanchen233** [comment]
Testing endpoint is removed, we keep old endpoint: `/api/data-stream-service-zip`
