### ISSUE TITLE
Multiple invitations to the same study

### ISSUE THREAD

**Issue by xelahalo** [cph-cachet/carp-webservices-spring#11]
Look into why there are multiple invitations on some studies (maybe they are not getting deleted or it has to do with a person being assigned to multiple participant groups).

**Comment by cammdu** [comment]
This isn't due to multiple participant groups being created... will keep testing

**Comment by yuanchen233** [comment]
Is this related to #141 ? Participants has access to other participants' invitation within the same deployment (fixed).
