### ISSUE TITLE
Download from file endpoint returns 403 Forbidden -  Access Denied 

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-webservices-spring#111]
As a `Participant` I upload a file, but when trying to download it, I get

```
CarpServiceException: 403 Forbidden -  Access Denied - GET /api/studies/b7a4d433-c267-4d2c-b182-67bbbc37279b/files/17/download
```

using the `download` endpoint = `/api/studies/{study-id}/files/{file-id}/download`

The get endpoint works fine = `/api/studies/{study-id}/files/{file-id}`.

Testing on `DEV`.

**Comment by yuanchen233** [comment]
Tested with Researcher/Admin account, download endpoint works, FileOwner Claim works,
todo: test with participant account

**Comment by yuanchen233** [comment]
JWT token does not include `FileOwner` Claim for participant, however, it is set correctly and works properly for researchers.
Look into situations where JWT token generation is different for participant and researcher

**Comment by davidscavnicky** [comment]
Tested with Participant/Admin account. Need to look into scenario for Participant

**Comment by yuanchen233** [comment]
need to refresh token

**Comment by davidscavnicky** [comment]
after assigning fileOwner attribute to participant's token (upload), the token needs to be refreshed and get from Keycloak via already established endpoint.
backend's setting and getting of attribute from generated JWT token works correctly, when creating access to file system.

**Comment by bardram** [comment]
Update the Swagger API documentation to include this information.

**Comment by davidscavnicky** [comment]
Swagger API documentation updated
