### ISSUE TITLE
Filename of summary files 

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-webservices-spring#15]
There are several issues with the filenames of the summary download

1. The filename listed on the portal does not correspond to the name of the file downloaded. For example in the picture below, the name of the file downloaded is `0b16ed88-7492-3c97-9eb5-e085fd01eea9.zip` and not what is shown on the portal.
2. The name of the file should be `<study_id>_<date_time_of_generation>.zip`.
3. The list of measurement in the zip file is right now called `dataPointSequences.json` but should be named `data-streams.json` to comply to the naming scheme of the other files.

![image](https://github.com/cph-cachet/carp-webservices-spring/assets/1196642/71b46d68-a774-4501-bc41-1ed949273c15)

**Comment by davidscavnicky** [comment]
fixed by https://github.com/cph-cachet/carp-webservices-spring/pull/18
