### ISSUE TITLE
HTTP Error 413

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-webservices-spring#166]
Trying to upload an image on 13 MB I get an HTTP error 413

```
{
 "type": "about:blank",
 "title": "Payload Too Large",
 "status": 413,
 "detail": "Maximum upload size exceeded",
 "instance": "/api/studies/b7a4d433-c267-4d2c-b182-67bbbc37279b/files",
 "properties": null
}
```

We should be able to upload files & images.

**Comment by yuanchen233** [comment]
This is defined in `application.yml` under `spring.servlet.multipart.maxfile-size` and `max-request-size`.

change this on environment specific yml files and re-deploy once we agrees to a new maximum. ps: consider videos also

**Comment by bardram** [comment]
Set it to 30 MB for now.
