### ISSUE TITLE
Claims are not granted when inviting participant by email

### ISSUE THREAD

**Issue by yuanchen233** [cph-cachet/carp-webservices-spring#179]
The `inDeployment` Claim is not granted correctly to participants invited through email.
This results for all endpoints require this claim to fail, including 'required participant data'

This only happens for new users

**Comment by pavliuc75** [comment]
This happens if the keycloak realm email settings is not configured. So when keyloak api endpoint execute-actions-email is called, the request fails. 
I have try catched that block of code. This is because the method might be called in the loop and the other emails still need to be handled.
