### ISSUE TITLE
Sometimes the server responds with HTML instead of JSON errors

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-webservices-spring#24]
Sometimes I get HTML like below for some errors, which makes the deserialization break, since it expects a JSON-formatted error message.

```
RESPONSE: 502
      <html>
      <head><title>502 Bad Gateway</title></head>
      <body>
      <center><h1>502 Bad Gateway</h1></center>
      <hr><center>nginx/1.18.0 (Ubuntu)</center>
      </body>
      </html>
```

**Comment by xelahalo** [comment]
This is an error produced by the Nginx reverse proxy. The server was most likely down because of a deployment.
