### ISSUE TITLE
The AppendToDataStream endpoint is EXTREMLY slow....

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-webservices-spring#36]
I've updated the Dart unit tests for the data sub-system, and the AppendToDataStream endpoint takes 9-10 seconds for a very simple batch consisting of two measurements.

This can't be true.... And it in any case should work async.....

**Comment by yuanchen233** [comment]
This is caused by 'memory consumption issues' mentioned here,
[https://trello.com/c/aw7NESPG/655-memory-leak-of-carpwebservices?search_id=20853748-f5bd-4c46-a4ac-dbc1d66ed533](url)
It is fixed by #32 .

**Comment by xelahalo** [comment]
Fixed by #32
