### ISSUE TITLE
Create anonymous accounts as a background process the state of which can be polled

### ISSUE THREAD

**Issue by xelahalo** [cph-cachet/carp-webservices-spring#51]
The feature that was done in Anonymous Accounts / Participants exposes an endpoint that is able to create anonymous participants for studies (#49).

However, the endpoint is not suitable to generate large amounts of participants for studies (mainly due to its synchronous nature). Therefore the ideal way to do this kind of feature would be to:

* Let N number of accounts be created by the Keycloak magic-link endpoint in parallel and

* Running the process in the background and exposing polling to check whether the process is finished or not

- [ ] Let N number of accounts be created by the Keycloak magic-link endpoint in **parallel**
- [ ] Run the process in the background and put the CSV file with the generated accounts for download
- [ ] Add an entry in the Summary table about the file + status (maybe rename this table to something like "Exports"?)
- [ ] Show an "Accounts being generated" view in the portal showing an estimated time plus that the file will be available in the "export" page.
- [ ] Add the CSV file to the list of files to be downloaded in the "exports" page

**Comment by yuanchen233** [comment]
Fix in #65
