### ISSUE TITLE
Revisit onboarding flow

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-webservices-spring#59]
In the current onboarding flow, the user gets two emails:

1. Update Your Account
2. Study Invitation

We need to revise the wording of these emails and **merge them into one email**.

## Update Your Account

<img width="755" alt="image" src="https://github.com/cph-cachet/carp-webservices-spring/assets/1196642/601ee192-f388-4e9f-b49a-c58016ff15a8">

<img width="1076" alt="image" src="https://github.com/cph-cachet/carp-webservices-spring/assets/1196642/62cb879d-e3f1-4c0c-8d14-cba6f7e01980">

<img width="1087" alt="image" src="https://github.com/cph-cachet/carp-webservices-spring/assets/1196642/ab5502cc-6e62-447c-acff-e6fe3e4013c0">

Issues:

* Why is this update needed? Why does the user get this email?
* This needs to be available in Danish too.
* Why the screen with the one button - if only one thing can be done, then why this intermediate step?
* Why do the user need to change their password (this is not my experience that this is needed)?
* If needed, how can the user specify her/his full name?

## Study Invitation

<img width="793" alt="image" src="https://github.com/cph-cachet/carp-webservices-spring/assets/1196642/3b9ee110-21f9-4fe5-966e-383a30c5279d">

Issues:

* This email needs an update - we are no longer "CACHET" but "CARP", etc.
* The font is terrible - too big and cluncky
* Images look terrible (omit those)

**Comment by xelahalo** [comment]
Add the language selection required action on new account invitation.

**Comment by xelahalo** [comment]
Take the required actions out if the account that is being invited is not new.

**Comment by yuanchen233** [comment]
Changed email style at #74 and #71
