### ISSUE TITLE
GetDataStream end point is throwing strange exception - "Sequence range start lies before the end of a previously appended sequence to the same data stream.",

### ISSUE THREAD

**Issue by bardram** [cph-cachet/carp-webservices-spring#73]
When calling `DataStreamServiceRequest.GetDataStream` to get a set of data stream, the server throws a strange exception which has nothing to do with getting data (more related to appending data I would think). 

So - can't really get any data....

```
[log] [CAMS DEBUG] REQUEST: https://dev.carp.dk/api/data-stream-service
      {
       "__type": "dk.cachet.carp.data.infrastructure.DataStreamServiceRequest.GetDataStream",
       "apiVersion": "1.1",
       "dataStream": {
        "studyDeploymentId": "04f7c048-c322-4939-a660-be95b0dd3681",
        "deviceRoleName": "Participant's phone",
        "dataType": "dk.cachet.carp.batterystate"
       },
       "fromSequenceId": 0,
       "toSequenceIdInclusive": 100
      }
[log] [CAMS DEBUG] RESPONSE: 400
      {"statusCode":400,"exception":"java.lang.IllegalArgumentException","message":"Sequence range start lies before the end of a previously appended sequence to the same data stream.","path":"POST /api/data-stream-service"}
```

**Comment by bardram** [comment]
Make our own `CAWSMutableDataStreamBatch` implementation of the `DataStreamBatch` interface that DOES NOT check for all the sequence IDs in the append methods.

**Comment by davidscavnicky** [comment]
https://github.com/cph-cachet/carp-webservices-spring/pull/77

- I have made the workaround based on what we discussed.

**Comment by davidscavnicky** [comment]
the pull request can't merged before we fix: 

verify pull requests / build (pull_request) Failing after 35s @xelahalo  @yuanchen233 
automated checks and build before merged (somehow fails)
