### ISSUE TITLE
Occasional 502 Bad Gateway error when trying to authenticate

### ISSUE THREAD

**Issue by SlimShadyIAm** [cph-cachet/carp-webservices-spring#81]
Sometimes when trying to sign in on e.g the study app, I get a 502 bad gateway error (see below):

![image](https://github.com/cph-cachet/carp-webservices-spring/assets/10660846/a700e9d1-1b1b-45ab-bd79-78e5d56c30f8)

I looked into it and the solution in this thread might help: https://stackoverflow.com/questions/56126864/why-do-i-get-502-when-trying-to-authenticate

**Comment by yuanchen233** [comment]
Buffer size increased
