### ISSUE TITLE
Upgrade dependencies to fix warnings

### ISSUE THREAD

**Issue by davidscavnicky** [cph-cachet/carp-webservices-spring#82]
need to review dependencies vulnerability for CAWS.

Building a project is not enough locally. Difference in dates of dependencies can ruin functionality and security. (/*)
have a ready scheme for build release before major update!

check all corners for upcoming months as develop can progress

consider way and create roadmap to Kotlin 2.0 .

**Comment by yuanchen233** [comment]
Duplicate #80, though, dependencies check fx. setup Dependabot would be nice.
Kotlin 2.0 should be considered only after carp.core adopts it.
